# Language setting http://docs.shippable.com/ci/languages/node/
language: python

# use this to control what branches get built.
# http://docs.shippable.com/ci/advancedOptions/branches/
branches:
  only:
    - master

jobs:
  - name: sample-job-A
    type: runSh
    steps:
      - TASK:
          script:
            - print datetime.datetime.now()
