# Language setting http://docs.shippable.com/ci/languages/node/
language: python

# use this to control what branches get built.
# http://docs.shippable.com/ci/advancedOptions/branches/
branches:
  only:
    - master

jobs:

  - name: container_single_task
    type: runSh
    steps:
      - TASK:
          name: task
          script:
             - date   
